name: Build container image, publish as GitHub-package

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ main, develop ]
    # Publish semver tags as releases.
    tags:
      - 'v*.*.*'
    workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Start a local Docker Builder
        run: |
          docker run --rm -d --name buildkitd -p 1234:1234 --privileged moby/buildkit:latest --addr tcp://0.0.0.0:1234

      - name: Configure Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: remote
          endpoint: tcp://localhost:1234
          platforms: linux/amd64
          append: |
            - endpoint: tcp://${{ secrets.ARM64_BUILDER_HOST }}:${{ secrets.ARM64_BUILDER_PORT }}
              platforms: linux/arm64
              name: ${{ secrets.ARM64_BUILDER_NAME }}
              driver-opts:
                - servername=${{ secrets.ARM64_BUILDER_NAME }}
        env:
          BUILDER_NODE_1_AUTH_TLS_CACERT: ${{ secrets.ARM64_BUILDER_CACERT }}
          BUILDER_NODE_1_AUTH_TLS_CERT: ${{ secrets.ARM64_BUILDER_CERT }}
          BUILDER_NODE_1_AUTH_TLS_KEY: ${{ secrets.ARM64_BUILDER_KEY }}

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: |
            ghcr.io/${{ github.repository }}
          flavor: latest=true

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker images
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
